### ISSUE TITLE
Hide actions that cannot be used in the current RSP state

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-rsp#95]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

The context menu shows actions that are not enabled because of the current server state.
For example, if my rsp server is stopped, the  `Download/Update RSP`, `Stop RSP`, `Create Server` and `Download Server` can be hidden
![image](https://user-images.githubusercontent.com/49404737/118477323-dc658d00-b70e-11eb-9e7a-bcecc2080c65.png)

The same when a RSP is missing.
In this case there is also the `Stop RSP` that is wrongly enabled
![image](https://user-images.githubusercontent.com/49404737/118477702-41b97e00-b70f-11eb-8920-6afb606e149f.png)

The same when a RSP is started
![image](https://user-images.githubusercontent.com/49404737/118477851-74fc0d00-b70f-11eb-8134-b31966bb59bc.png)

## Why is this needed? 
To be in sync with vscode and because you know it is the right thing to do :laughing:

**Comment by robstryker** [comment]
>  In this case there is also the Stop RSP that is wrongly enabled
I am fixing this issue.

As for the rest, I fundamentally disagree with you. It is appropriate to show a consistent set of menu items when those items are the standard actions for the selection. Actions that can never be used with a selection might be hidden, but actions that can usually be used with a selection should be disabled instead of 'disappearing' and leaving a user confused as to where the action has gone. 

https://www.eclipse.org/webtools/releases/2.0/newandnoteworthy/server/clean.png

See wtp servertools: When the server is started, the start and profile action items are disabled, but still there.
